name: Scanner CI
on:
  pull_request:
    paths:
      - "apcop/**"
      - "tests/**"
      - "pyproject.toml"
  push:
    branches: [ main ]
    paths:
      - "apcop/**"
      - "tests/**"
      - "pyproject.toml"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install package + test deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .[pro]
          pip install pytest

      - name: Run tests
        run: pytest -q
